# Change these first
owner: justin-sumner # Your GitHub organization or username, where this repository lives
repo: uky-upptime # The name of this repository

sites:
  - name: UK Home
    url: https://www.uky.edu
  - name: Undergraduate Admissions
    url: https://admission.uky.edu
  - name: Transportation
    url: https://transportation.uky.edu
  - name: Student Success
    url: https://studentsuccess.uky.edu
  - name: College of Engineering
    url: https://engr.uky.edu
  - name: College of Arts and Sciences
    url: https://as.uky.edu
  - name: College of Business and Economics
    url: https://gatton.uky.edu
  - name: College of Agriculture Food and Environment
    url: https://cafe.uky.edu
  - name: College of Fine Arts
    url: https://finearts.uky.edu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uky-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: University of Kentucky Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
